export const ACTION_TYPES = {
    CARDS: 'cards',
    CLICK_CARD: 'click-card',
    SHUFFLE: 'shuffle',
    NEW_BOARD: 'new-board',
    RESTART: 'restart',
    LOGIN: 'login',
    TEAMS: 'teams',
    SET_BOSS: 'set-boss',
    BOSS: 'boss',
    LOGOUT: 'logout',
    LOGOUT_ME: 'logout-me',
    SWITCH_TEAM: 'switch-team',
    START: 'start',
    END: 'end',
}